-- ═══════════════════════════════════════════════════════════════════════════════
-- 0034 · DE ENE REVISIERONDE, ALS FEIT IN PLAATS VAN ALS ZIN
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- ── DE BELOFTE BESTOND, DE KOLOM NIET ───────────────────────────────────────
--
-- `AFTERCARE` in src/data/pricing.js belooft *"1 revision round included per
-- order"*. Die belofte staat op /faq, op /pricing, op elke dienstpagina, in de
-- vergelijking met een fotoshoot, en sinds 25 augustus 2026 ook in de claimregel
-- onder de knoppen op de homepage.
--
-- `revisionRoundState()` in datzelfde bestand is die belofte als code, met vijf
-- toestanden en een zorgvuldige noot erboven over waarom het geen boolean is.
-- Die functie leest `order.revision_round_at`.
--
-- DIE KOLOM BESTOND NERGENS. Niet in schema.sql, niet in drieëndertig migraties.
-- Gevolg: `revisionRoundState()` gaf voor élke bestelling 'beschikbaar' terug
-- zolang hij niet gesloten was, `canRequestRevisionRound()` zei altijd ja, en
-- allebei werden ze door geen enkel scherm aangeroepen. Een klant kon in het
-- dashboard onbeperkt beelden aanmerken; er werd nooit iets afgeschreven.
--
-- Deze migratie is de kolom waar die functie al die tijd naar zocht.
--
-- ── ÉÉN KOLOM OP `orders` EN GEEN EIGEN TABEL ───────────────────────────────
--
-- Wat hier bewaard wordt is precies één feit: WANNEER de ronde is ingediend. De
-- inhoud van die ronde staat al ergens — `revision_requests` bewaart per beeld
-- een notitie met `file_id`, `order_id`, `customer_id` en `created_at`, en
-- `files.review_note` draagt dezelfde tekst als toestand van dat ene beeld.
--
-- Een eigen tabel `revision_rounds` zou meerdere rondes per bestelling toelaten,
-- en dat is nu juist het ding dat niet mag. De belofte is ÉÉN ronde. Een schema
-- dat er twee toestaat, nodigt uit tot een tweede — en dan is de vraag "hoeveel
-- heeft deze klant er gehad" ineens een telling in plaats van een blik.
--
-- Wil de studio ooit een tweede ronde weggeven, dan is dat een uitzondering die
-- iemand met de hand maakt: `UPDATE orders SET revision_round_at = NULL`. Dat is
-- zichtbaar, opzettelijk, en het laat geen spoor achter dat op beleid lijkt.
--
-- ── NULL BETEKENT "NOG NIET", EN DAT IS DE NORMALE TOESTAND ─────────────────
--
-- Elke bestaande bestelling krijgt NULL, en dat klopt: er is nooit een ronde
-- ingediend, want er was niets om hem in te dienen. Klanten die vóór vandaag
-- beelden hebben aangemerkt, houden hun aanmerkingen — die staan in
-- `revision_requests` en in `files.review_state` — en hun ronde staat vanaf nu
-- open. Dat is de vriendelijke kant om fout te gaan: niemand raakt met
-- terugwerkende kracht iets kwijt dat hij niet wist te hebben.
--
-- ── GEEN INDEX ──────────────────────────────────────────────────────────────
--
-- Bewust. De enige vraag die op deze kolom gesteld wordt is "wat staat er op DEZE
-- bestelling", en die komt altijd binnen via `orders.id` of `orders.ref` — beide
-- al geïndexeerd. Er wordt nooit gezocht op "alle bestellingen met een gebruikte
-- ronde"; het beheerscherm toont de revisies uit `revision_requests`, dat zijn
-- eigen indexen heeft. Een index die niemand raakt, kost alleen schrijfsnelheid.
--
-- ── WAT ER BUITEN DEZE MIGRATIE OM MEEKOMT ──────────────────────────────────
--
-- src/lib/account.js krijgt de indienvorm: aanvinken per beeld, een notitie per
-- aangevinkt beeld, één knop onderaan die de hele ronde tegelijk verstuurt, en
-- daarboven het blok dat zegt wat er gebeurt als je erop drukt. Goedkeuren blijft
-- per beeld en direct — dat verbruikt niets en hoort geen drempel te krijgen.

ALTER TABLE orders ADD COLUMN revision_round_at TEXT;
