// Vervolg van het abonnement: maand 2 incasseren, mislukte incasso, pauzeren, hervatten, opzeggen.
import { start, foto, tekst, mails, mailtekst, sql, paneel, SITE } from './_dl.mjs';
import { studioLogin } from './_studio.mjs';
const toonMails = async (voor) => { for (const m of (await mails()).slice(voor)) { console.log(`MAIL #${m.n} → ${JSON.stringify(m.to)} "${m.subject}"`); console.log((await mailtekst(m.n)).slice(0, 900)); } };
const subs = await paneel('/subs'); const sub = subs[subs.length - 1];
let voor = (await mails()).length;
console.log('## maand 2 incasseren');
console.log(JSON.stringify((await paneel(`/sub/${sub.id}/charge?op=2026-10-23`, { method: 'POST' })).webhook));
await toonMails(voor);
console.log(await sql('SELECT month, kind, granted, used FROM subscription_slots WHERE subscription_id=(SELECT MAX(id) FROM subscriptions)'));
voor = (await mails()).length;
console.log('## maand 3 mislukt');
console.log(JSON.stringify((await paneel(`/sub/${sub.id}/charge?op=2026-11-23&status=failed`, { method: 'POST' })).webhook));
await toonMails(voor);
console.log(await sql('SELECT status, paused_at, pause_reason FROM subscriptions WHERE id=(SELECT MAX(id) FROM subscriptions)'));
const s = await start(); const { page } = s;
await studioLogin(page, 'yara@merk.test');
await page.goto(SITE + '/account/plan?tab=facturering', { waitUntil: 'load' });
voor = (await mails()).length;
console.log('## pauzeren');
await Promise.all([page.waitForNavigation({ waitUntil: 'load' }), page.locator('button:has-text("PAUZEREN"), button:has-text("pauzeren")').first().click()]);
console.log(page.url()); console.log((await tekst(page, 'main')).replace(/\n{2,}/g, '\n').slice(0, 1400));
await foto(page, 'abo-gepauzeerd', { vol: true });
console.log(await sql('SELECT status, paused_at, pause_reason FROM subscriptions WHERE id=(SELECT MAX(id) FROM subscriptions)'));
console.log(await paneel('/subs').then((l) => l.map((x) => x.status)));
console.log('## hervatten');
const herv = page.locator('button:has-text("HERVATTEN"), button:has-text("hervatten"), button:has-text("Hervat")');
console.log('hervat-knoppen:', await herv.count());
if (await herv.count()) { await Promise.all([page.waitForNavigation({ waitUntil: 'load' }), herv.first().click()]); console.log(page.url()); console.log((await tekst(page, 'main')).replace(/\n{2,}/g, '\n').slice(0, 1200)); }
console.log(await sql('SELECT status, paused_at, mollie_subscription_id FROM subscriptions WHERE id=(SELECT MAX(id) FROM subscriptions)'));
console.log(await paneel('/subs').then((l) => l.map((x) => `${x.id}:${x.status}:${x.startDate}`)));
console.log('## opzeggen');
await page.goto(SITE + '/account/plan?tab=facturering', { waitUntil: 'load' });
await page.fill('input[name="confirm"]', 'OPZEGGEN');
await Promise.all([page.waitForNavigation({ waitUntil: 'load' }), page.locator('button:has-text("OPZEGGEN"), button:has-text("opzeggen")').last().click()]);
console.log(page.url()); console.log((await tekst(page, 'main')).replace(/\n{2,}/g, '\n').slice(0, 1400));
await foto(page, 'abo-opgezegd', { vol: true });
console.log(await sql('SELECT status, cancelled_at, cancel_reason FROM subscriptions WHERE id=(SELECT MAX(id) FROM subscriptions)'));
console.log(await paneel('/subs').then((l) => l.map((x) => `${x.id}:${x.status}`)));
await toonMails(voor);
console.log(s.fouten);
await s.stop();
