import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1180, height: 1000 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto('file:///home/claude/repo/kladblok/kledingproef/index.html', { waitUntil: 'load' });
await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(600);
await p.screenshot({ path: 'kladblok/kledingproef/alles.png', fullPage: true });
const s = await p.$$('.sectie');
for (let i = 0; i < s.length; i++) await s[i].screenshot({ path: `kladblok/kledingproef/deel-${i + 1}.png` });
await b.close(); console.log('ok');
